<?xml version="1.0" encoding="utf-8"?><Database Name="TTNHOM_QUANLIBANQUANAO" Class="QuanaoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DELL\SQLEXPRESS;Initial Catalog=TTNHOM_QUANLIBANQUANAO;Integrated Security=True" SettingsObjectName="CUAHANGQUANAO.Properties.Settings" SettingsPropertyName="TTNHOM_QUANLIBANQUANAOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="USERNAME" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChungLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIETHOADON" />
      <Association Name="SANPHAM_CHITIETNHAP" Member="CHITIETNHAPs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIETNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.NCC" Member="NCCs">
    <Type Name="NCC">
      <Column Name="MaNCC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Association Name="NCC_CHITIETNHAP" Member="CHITIETNHAPs" ThisKey="MaNCC" OtherKey="MaNCC" Type="CHITIETNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MaHD" OtherKey="MaHoaDon" Type="CHITIETHOADON" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MaCTHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaHoaDon" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MaHoaDon" OtherKey="MaHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="MaPN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VAT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaNhomHang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CHITIETNHAP" Member="CHITIETNHAPs" ThisKey="MaPN" OtherKey="MaPN" Type="CHITIETNHAP" />
      <Association Name="NHANVIEN_PHIEUNHAP" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHOMHANG_PHIEUNHAP" Member="NHOMHANG" ThisKey="MaNhomHang" OtherKey="MaNhomHang" Type="NHOMHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETNHAP" Member="CHITIETNHAPs">
    <Type Name="CHITIETNHAP">
      <Column Name="MACTN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaPN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="NCC_CHITIETNHAP" Member="NCC" ThisKey="MaNCC" OtherKey="MaNCC" Type="NCC" IsForeignKey="true" />
      <Association Name="PHIEUNHAP_CHITIETNHAP" Member="PHIEUNHAP" ThisKey="MaPN" OtherKey="MaPN" Type="PHIEUNHAP" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETNHAP" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GT" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="NS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MaNV" OtherKey="MaNV" Type="HOADON" />
      <Association Name="NHANVIEN_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MaNV" OtherKey="MaNV" Type="PHIEUNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GT" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MaKH" OtherKey="MaKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.NHOMHANG" Member="NHOMHANGs">
    <Type Name="NHOMHANG">
      <Column Name="MaNhomHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhomHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHOMHANG_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MaNhomHang" OtherKey="MaNhomHang" Type="PHIEUNHAP" />
    </Type>
  </Table>
</Database>